# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirgo < Formula
  desc "Fast, interactive terminal directory analyzer"
  homepage "https://github.com/mohsinkaleem/dirgo"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.2.0/dirgo_1.2.0_darwin_amd64.tar.gz"
      sha256 "25e9bce6db946fe843acbe1ede5e0901306211d00992962c6586838177303416"

      define_method(:install) do
        bin.install "dirgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.2.0/dirgo_1.2.0_darwin_arm64.tar.gz"
      sha256 "53b59b67543aa9585ef92d67148ed1c381c4f0c27a58dcea88ecfc87f0968f8a"

      define_method(:install) do
        bin.install "dirgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.2.0/dirgo_1.2.0_linux_amd64.tar.gz"
      sha256 "9506240aaae15dc874975eba320710c53ee39a59b147e2abeae5bbac804fe0bd"
      define_method(:install) do
        bin.install "dirgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.2.0/dirgo_1.2.0_linux_arm64.tar.gz"
      sha256 "2ff9973cb7459a4c9b20dc8b3249b16c4d52fea971ed2d587dbbaf54ab3dc08d"
      define_method(:install) do
        bin.install "dirgo"
      end
    end
  end
end
