# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirgo < Formula
  desc "Fast, interactive terminal directory analyzer"
  homepage "https://github.com/mohsinkaleem/dirgo"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.1.0/dirgo_1.1.0_darwin_amd64.tar.gz"
      sha256 "44e33412903ec86ac84519b74c2b75cd30d2478049a274ab40c5a6c1a7b9ea5a"
    end
    on_arm do
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.1.0/dirgo_1.1.0_darwin_arm64.tar.gz"
      sha256 "313f9e22d48862d9dd572dcb13265ad83d89f018802da17bc26e7d78b4e2f0fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.1.0/dirgo_1.1.0_linux_amd64.tar.gz"
      sha256 "a618e13a5fa3b62d1454f70fc3d46cee8b4d7e5eebf3fc3641cab86db35449e5"
    end
    on_arm do
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v1.1.0/dirgo_1.1.0_linux_arm64.tar.gz"
      sha256 "a094a99585ca0888db0449bed71884ab3b412dfaae35ddbd007b16a30c074e44"
    end
  end

  def install
    bin.install "dirgo"
  end

  test do
    assert_match "dirgo", shell_output("#{bin}/dirgo --version")
  end
end
