# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirloc < Formula
  desc "A fast CLI tool that counts lines of code and reports top files/directories by size"
  homepage "https://github.com/mohsinkaleem/dirloc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohsinkaleem/dirloc/releases/download/v0.1.0/dirloc_0.1.0_darwin_amd64.tar.gz"
      sha256 "f1ddec1048c58058581c0fee97b54d69653574d083d4edab30a57a2c7e989528"

      define_method(:install) do
        bin.install "dirloc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohsinkaleem/dirloc/releases/download/v0.1.0/dirloc_0.1.0_darwin_arm64.tar.gz"
      sha256 "7ed3f1d1c978649553baf0f5226b7e4d615ba1e283373ac2ab7803ba5ac4567c"

      define_method(:install) do
        bin.install "dirloc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohsinkaleem/dirloc/releases/download/v0.1.0/dirloc_0.1.0_linux_amd64.tar.gz"
      sha256 "824952349c632d43450e2d57a37b6554cacb9be0e6899d1b370b3af2f5bee2d4"
      define_method(:install) do
        bin.install "dirloc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohsinkaleem/dirloc/releases/download/v0.1.0/dirloc_0.1.0_linux_arm64.tar.gz"
      sha256 "668870ee8d74789ef1977433eb1f7cd518d23dd5cfc639c57271ec31ca9f8f0e"
      define_method(:install) do
        bin.install "dirloc"
      end
    end
  end

  test do
    system bin/"dirloc", "--help"
  end
end
