# This file was generated by GoReleaser. DO NOT EDIT.
cask "dirgo" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "6afe7d899cc583581a18ee21be4d2a3819b63be0f22361f22a800e888fab3735"
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v#{version}/dirgo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ace24edf2c89ef1b442a75aaa1cc3dd3b9f3f7bb7778d4f62cd3f514924a04e"
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v#{version}/dirgo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5fbf46498c92e85bac23fde4d94ea65039453f106cbce26231e15c6b66b29698"
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v#{version}/dirgo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a3a1dfec25e24c19bfca4ef204a0ad300ef3dd5f6da25dce8a8739fa680a989"
      url "https://github.com/mohsinkaleem/dirgo/releases/download/v#{version}/dirgo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dirgo"
  desc "Fast, interactive terminal disk usage analyzer"
  homepage "https://github.com/mohsinkaleem/dirgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dirgo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dirgo"]
    end
  end

  # No zap stanza required
end
