# This file was generated by GoReleaser. DO NOT EDIT.
cask "ytui" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "9446bd3c53770bf62f2557e2288b8161cf39ed92adbdc52576b3a6eb9803fda2"
      url "https://github.com/mohsinkaleem/ytui-go/releases/download/v#{version}/ytui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9e273196e498bb355099742d68638a6937c2b5a055bc2366f1bd565d2e497db"
      url "https://github.com/mohsinkaleem/ytui-go/releases/download/v#{version}/ytui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "387c2d257f1a1b545c681e0580d084f170228e4bcfdf01a2b956bfbd842a1b40"
      url "https://github.com/mohsinkaleem/ytui-go/releases/download/v#{version}/ytui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1138585a8cc88103c1f0a57e594880cb6c7f6855448bec60af11228b716d6778"
      url "https://github.com/mohsinkaleem/ytui-go/releases/download/v#{version}/ytui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ytui"
  desc "Terminal UI for yt-dlp: search, download and stream YouTube videos"
  homepage "https://github.com/mohsinkaleem/ytui-go"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "yt-dlp",
    ]

  binary "ytui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ytui"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended: ffmpeg to merge video and audio streams, mpv to stream videos (brew install ffmpeg mpv)
  EOS
end
